export const VIEW_COMMENTS_REQUEST = "VIEW_COMMENTS_REQUEST";
export const VIEW_COMMENTS_SUCCESS = "VIEW_COMMENTS_SUCCESS";
export const VIEW_COMMENTS_FAIL = "VIEW_COMMENTS_FAIL";
export const VIEW_COMMENTS_RESET = "VIEW_COMMENTS_RESET";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";
export const ADD_COMMENT_RESET = "ADD_COMMENT_RESET";

export const VIEW_COMMENTS_BY_HIGHLIGHT_REQUEST =
   "VIEW_COMMENTS_BY_HIGHLIGHT_REQUEST";
export const VIEW_COMMENTS_BY_HIGHLIGHT_SUCCESS =
   "VIEW_COMMENTS_BY_HIGHLIGHT_SUCCESS";
export const VIEW_COMMENTS_BY_HIGHLIGHT_FAIL =
   "VIEW_COMMENTS_BY_HIGHLIGHT_FAIL";
export const VIEW_COMMENTS_BY_HIGHLIGHT_RESET =
   "VIEW_COMMENTS_BY_HIGHLIGHT_RESET";
