export const VIEW_HIGHLIGHTS_REQUEST = "VIEW_HIGHLIGHTS_REQUEST";
export const VIEW_HIGHLIGHTS_SUCCESS = "VIEW_HIGHLIGHTS_SUCCESS";
export const VIEW_HIGHLIGHTS_FAIL = "VIEW_HIGHLIGHTS_FAIL";
export const VIEW_HIGHLIGHTS_RESET = "VIEW_HIGHLIGHTS_RESET";

export const VIEW_HIGHLIGHTS_BY_PDF_REQUEST = "VIEW_HIGHLIGHTS_BY_PDF_REQUEST";
export const VIEW_HIGHLIGHTS_BY_PDF_SUCCESS = "VIEW_HIGHLIGHTS_BY_PDF_SUCCESS";
export const VIEW_HIGHLIGHTS_BY_PDF_FAIL = "VIEW_HIGHLIGHTS_BY_PDF_FAIL";
export const VIEW_HIGHLIGHTS_BY_PDF_RESET = "VIEW_HIGHLIGHTS_BY_PDF_RESET";

export const ADD_HIGHLIGHT_REQUEST = "ADD_HIGHLIGHT_REQUEST";
export const ADD_HIGHLIGHT_SUCCESS = "ADD_HIGHLIGHT_SUCCESS";
export const ADD_HIGHLIGHT_FAIL = "ADD_HIGHLIGHT_FAIL";
export const ADD_HIGHLIGHT_RESET = "ADD_HIGHLIGHT_RESET";
