export const PDF_DETAILS_REQUEST = "PDF_DETAILS_REQUEST";
export const PDF_DETAILS_SUCCESS = "PDF_DETAILS_SUCCESS";
export const PDF_DETAILS_FAIL = "PDF_DETAILS_FAIL";
export const PDF_DETAILS_RESET = "PDF_DETAILS_RESET";

export const PDF_UPLOAD_REQUEST = "PDF_UPLOAD_REQUEST";
export const PDF_UPLOAD_SUCCESS = "PDF_UPLOAD_SUCCESS";
export const PDF_UPLOAD_FAIL = "PDF_UPLOAD_FAIL";
export const PDF_UPLOAD_RESET = "PDF_UPLOAD_RESET";

export const PDF_LIST_REQUEST = "PDF_LIST_REQUEST";
export const PDF_LIST_SUCCESS = "PDF_LIST_SUCCESS";
export const PDF_LIST_FAIL = "PDF_LIST_FAIL";
export const PDF_LIST_RESET = "PDF_LIST_RESET";
